services:
  # 1. 存储服务 (RustFS)
  rustfs-storage:
    image: rustfs/rustfs:latest
    container_name: rustfs-storage
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./rustfs_data:/data
    env_file:
      - .env

  # 2. API 服务 (Node.js + Alpine)
  rustfs-api-server:
    image: edwarrdy/rustfs-api:latest
    container_name: rustfs-api-server
    restart: always
    depends_on:
      - rustfs-storage
    ports:
      - "3300:3300"
    volumes:
      - ./data:/app/data
    # 核心：只使用环境文件，所有的变量都从这里加载
    env_file:
      - .env
